name: core
description: Expatrio core package
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  app_settings: 5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  copy_with_extension: ^5.0.3
  dartz:
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^2.0.7
  get_it: ^7.3.0
  go_router: ^12.1.0
  injectable: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^1.3.0
  permission_handler: ^10.4.3
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
  uni_links: ^0.5.1
  webview_flutter: ^4.2.2
  animations: ^2.0.7
  retrofit: ^4.0.1
  url_launcher: ^6.1.14
  device_info_plus: ^9.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  copy_with_extension_gen: ^5.0.3
  build_runner: ^2.0.0
  go_router_builder: ^2.3.4
  retrofit_generator: ^7.0.8
  injectable_generator: ^2.1.6
